import jsPDF from 'jspdf'
import {
  drawCoverPage, drawPageHeader, drawSectionTitle, drawStatCards,
  drawTable, drawDisclaimer, checkPageBreak, addFooters,
  BRAND, DARK, GRAY, RED, PW, ML, MR, CW,
} from './pdfBranding'
import { formatRupeesPDF, formatCountPDF } from './currency'

function formatDate(d) {
  if (!d) return 'N/A'
  return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
}

function formatTime(d) {
  if (!d) return 'N/A'
  return new Date(d).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })
}

function filterLabel(filter) {
  if (!filter || filter.key === 'all') return 'All Time'
  const map = { '7d': 'Last 7 Days', '30d': 'Last 30 Days', '6m': 'Last 6 Months', '1y': 'Last 1 Year' }
  if (filter.key === 'custom' && filter.start) {
    return `${formatDate(filter.start)} - ${filter.end ? formatDate(filter.end) : 'Present'}`
  }
  return map[filter.key] || 'All Time'
}

const TITLE = 'STAYSPACE PLATFORM ANALYTICS REPORT'

export function generateAdminReport(data) {
  const doc = new jsPDF('p', 'mm', 'a4')
  doc._reportTitle = TITLE

  const {
    stats, filteredStats, filteredBookings, recentBookings,
    hosts, pendingHosts, complaints, analyticsData,
    topProperties, topCities, openComplaints, resolvedComplaints,
    cancellationRate, platformGrowth, filter, adminName,
  } = data

  const now = new Date()

  let y = drawCoverPage(doc, TITLE, 'Generated by StaySpace Admin Portal', [
    `Report Date: ${formatDate(now)}`,
    `Report Time: ${formatTime(now)}`,
    `Generated By: ${adminName || 'Admin'}`,
    `Reporting Period: ${filterLabel(filter)}`,
  ])

  y = drawSectionTitle(doc, y, 'PLATFORM OVERVIEW')
  y = drawStatCards(doc, y, [
    { label: 'Total Users', value: formatCountPDF(stats?.total_users ?? 0) },
    { label: 'Total Guests', value: formatCountPDF(stats?.total_guests ?? 0) },
    { label: 'Total Hosts', value: formatCountPDF(stats?.total_hosts ?? 0) },
    { label: 'Total Properties', value: formatCountPDF(stats?.total_properties ?? 0) },
    { label: 'Active Bookings', value: formatCountPDF(filteredStats?.active_bookings ?? stats?.active_bookings ?? 0) },
    { label: 'Completed Bookings', value: formatCountPDF(filteredStats?.completed_bookings ?? stats?.completed_bookings ?? 0) },
    { label: 'Cancelled Bookings', value: formatCountPDF(filteredStats?.cancelled_bookings ?? stats?.cancelled_bookings ?? 0) },
    { label: 'Pending Hosts', value: formatCountPDF(stats?.pending_hosts ?? 0), colorR: 245, colorG: 158, colorB: 11 },
    { label: 'Total Complaints', value: formatCountPDF(stats?.total_complaints ?? 0) },
    { label: 'Open Complaints', value: formatCountPDF(openComplaints ?? 0), colorR: 245, colorG: 158, colorB: 11 },
    { label: 'Total Reviews', value: formatCountPDF(stats?.total_reviews ?? 0) },
    { label: 'Platform Growth', value: platformGrowth || '0%' },
    { label: 'Cancellation Rate', value: `${cancellationRate || 0}%`, colorR: RED.r, colorG: RED.g, colorB: RED.b },
  ])

  y += 2
  y = drawSectionTitle(doc, y, 'REVENUE')
  y = drawStatCards(doc, y, [
    { label: 'Platform Revenue', value: formatRupeesPDF(stats?.total_revenue ?? 0), colorR: BRAND.r, colorG: BRAND.g, colorB: BRAND.b },
    { label: 'Monthly Revenue', value: formatRupeesPDF(stats?.revenue_this_month ?? 0) },
    { label: 'Host Revenue', value: formatRupeesPDF(stats?.host_revenue ?? 0) },
  ])

  const headerTitle = TITLE

  const userGrowth = stats?.user_growth || []
  if (userGrowth.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'USER GROWTH')
    y = drawTable(doc, y,
      ['Month', 'Users'],
      userGrowth.map(d => [d.month_label || d.month || '-', String(d.users ?? 0)])
    )
  }

  const hostGrowth = stats?.host_growth || []
  if (hostGrowth.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'HOST GROWTH')
    y = drawTable(doc, y,
      ['Month', 'Hosts'],
      hostGrowth.map(d => [d.month_label || d.month || '-', String(d.hosts ?? 0)])
    )
  }

  const bookingTrends = stats?.booking_trends || []
  if (bookingTrends.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'BOOKINGS TREND')
    y = drawTable(doc, y,
      ['Month', 'Bookings'],
      bookingTrends.map(d => [d.month || '-', String(d.count ?? 0)])
    )
  }

  const bookingStatusDist = stats?.booking_status_distribution || []
  if (bookingStatusDist.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'BOOKING STATUS')
    const total = bookingStatusDist.reduce((s, d) => s + (d.count || 0), 0) || 1
    y = drawTable(doc, y,
      ['Status', 'Count', 'Percentage'],
      bookingStatusDist.map(d => [d.status || '-', String(d.count ?? 0), `${((d.count / total) * 100).toFixed(1)}%`])
    )
  }

  const propertyTypeDist = stats?.property_type_distribution || []
  if (propertyTypeDist.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'PROPERTY TYPES')
    const total = propertyTypeDist.reduce((s, d) => s + (d.count || 0), 0) || 1
    y = drawTable(doc, y,
      ['Type', 'Count', 'Percentage'],
      propertyTypeDist.map(d => [d.type || '-', String(d.count ?? 0), `${((d.count / total) * 100).toFixed(1)}%`])
    )
  }

  const reviewAnalytics = stats?.review_analytics || []
  if (reviewAnalytics.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'REVIEWS BY RATING')
    const total = reviewAnalytics.reduce((s, d) => s + (d.count || 0), 0) || 1
    y = drawTable(doc, y,
      ['Rating', 'Count', 'Percentage'],
      reviewAnalytics.map(d => [`${d.rating} Star${d.rating !== 1 ? 's' : ''}`, String(d.count ?? 0), `${((d.count / total) * 100).toFixed(1)}%`])
    )
  }

  if (topCities && topCities.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'TOP CITIES')
    y = drawTable(doc, y,
      ['City', 'Bookings', 'Revenue'],
      topCities.map(d => [d.city || '-', String(d.bookings ?? 0), formatRupeesPDF(d.revenue ?? 0)])
    )
  }

  if (topProperties && topProperties.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'TOP PROPERTIES')
    y = drawTable(doc, y,
      ['Property', 'Host', 'Bookings', 'Rating', 'Revenue'],
      topProperties.map(d => [
        d.title || d.property_title || '-',
        d.host_name || '-',
        String(d.bookings ?? d.total_bookings ?? 0),
        d.avg_rating > 0 ? `${d.avg_rating}` : '-',
        formatRupeesPDF(d.revenue ?? 0),
      ])
    )
  }

  if (recentBookings && recentBookings.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'RECENT BOOKINGS')
    y = drawTable(doc, y,
      ['Booking ID', 'Guest', 'Host', 'Property', 'Check-in', 'Check-out', 'Status', 'Amount'],
      recentBookings.map(b => [
        `#${b.id ?? b.booking_id ?? '-'}`,
        b.guest_name || '-',
        b.host_name || '-',
        b.property_title || '-',
        b.check_in || '-',
        b.check_out || '-',
        b.status || '-',
        formatRupeesPDF(b.total_price ?? 0),
      ]),
      { columnStyles: { 7: { halign: 'right' } } }
    )
  }

  if (pendingHosts && pendingHosts.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'PENDING HOST APPROVALS')
    y = drawTable(doc, y,
      ['Host Name', 'Email', 'Registration Date', 'Status'],
      pendingHosts.map(h => [
        h.name || h.host_name || '-',
        h.email || h.host_email || '-',
        formatDate(h.created_at || h.registered_at || h.registration_date),
        h.status || '-',
      ])
    )
  }

  y = drawDisclaimer(doc, y)
  addFooters(doc)

  doc.save(`StaySpace-Admin-Report-${formatDate(now).replace(/\s/g, '-')}.pdf`)
}


