import jsPDF from 'jspdf'
import 'jspdf-autotable'
import {
  drawCoverPage, drawPageHeader, drawSectionTitle, drawStatCards,
  drawTable, drawDisclaimer, checkPageBreak, addFooters,
  BRAND, DARK, GRAY, PW, ML, MR, CW,
} from './pdfBranding'
import { formatRupees } from './currency'

function formatDate(d) {
  if (!d) return 'N/A'
  return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
}

function formatTime(d) {
  if (!d) return 'N/A'
  return new Date(d).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })
}

function filterLabel(filter) {
  if (!filter || filter.key === 'all') return 'All Time'
  const map = { '7d': 'Last 7 Days', '30d': 'Last 30 Days', '6m': 'Last 6 Months', '1y': 'Last 1 Year' }
  if (filter.key === 'custom' && filter.start) {
    return `${formatDate(filter.start)} - ${filter.end ? formatDate(filter.end) : 'Present'}`
  }
  return map[filter.key] || 'All Time'
}

const TITLE = 'STAYSPACE HOST PERFORMANCE REPORT'

export function generateHostReport(data) {
  const doc = new jsPDF('p', 'mm', 'a4')
  doc._reportTitle = TITLE

  const {
    stats, filteredStats, filteredBookings, recentBookings,
    checkins, reviews, chartData, filteredPropertyPerformance,
    filteredBookingStatusDist, avgOccupancy, filter,
  } = data

  const now = new Date()
  const headerTitle = TITLE

  let y = drawCoverPage(doc, TITLE, 'Generated by StaySpace Host Portal', [
    `Host Name: ${stats?.host_name || 'Host'}`,
    `Report Date: ${formatDate(now)}`,
    `Report Time: ${formatTime(now)}`,
    `Reporting Period: ${filterLabel(filter)}`,
  ])

  y = drawSectionTitle(doc, y, 'PROPERTIES')
  y = drawStatCards(doc, y, [
    { label: 'Total Properties', value: stats?.total_properties ?? 0 },
    { label: 'Top Performing Property', value: stats?.top_performing_property || 'N/A' },
  ])

  y += 2
  y = drawSectionTitle(doc, y, 'BOOKINGS')
  y = drawStatCards(doc, y, [
    { label: 'Total Bookings', value: filteredStats?.total_bookings ?? stats?.total_bookings ?? 0 },
    { label: 'Completed', value: filteredStats?.completed_bookings ?? stats?.completed_bookings ?? 0, colorR: 34, colorG: 197, colorB: 94 },
    { label: 'Pending', value: filteredStats?.pending_bookings ?? stats?.pending_bookings ?? 0, colorR: 245, colorG: 158, colorB: 11 },
    { label: 'Cancelled', value: filteredStats?.cancelled_bookings ?? stats?.cancelled_bookings ?? 0, colorR: 239, colorG: 68, colorB: 68 },
  ])

  y += 2
  y = drawSectionTitle(doc, y, 'REVENUE')
  y = drawStatCards(doc, y, [
    { label: 'Monthly Revenue', value: formatRupees(stats?.monthly_earnings ?? 0), colorR: BRAND.r, colorG: BRAND.g, colorB: BRAND.b },
    { label: 'Annual Revenue', value: formatRupees(stats?.annual_earnings ?? 0) },
  ])

  y += 2
  y = drawSectionTitle(doc, y, 'SATISFACTION')
  y = drawStatCards(doc, y, [
    { label: 'Average Rating', value: stats?.average_rating?.toFixed(1) || '0.0', colorR: 245, colorG: 158, colorB: 11 },
    { label: 'Occupancy Rate', value: `${avgOccupancy ?? 0}%` },
    { label: 'Rating Change', value: stats?.rating_change != null ? `${stats.rating_change >= 0 ? '+' : ''}${stats.rating_change.toFixed(1)}` : 'N/A' },
  ])

  if (chartData && chartData.length > 0) {
    y = checkPageBreak(doc, y, 50, headerTitle)
    y = drawSectionTitle(doc, y, 'REVENUE TREND')
    y = drawTable(doc, y,
      ['Month', 'Earnings', 'Bookings', 'Occupancy'],
      chartData.map(d => [
        d.month_label || '-',
        formatRupees(d.earnings ?? 0),
        String(d.bookings ?? 0),
        `${d.occupancy ?? 0}%`,
      ])
    )
  }

  if (chartData && chartData.length > 0) {
    y = checkPageBreak(doc, y, 50, headerTitle)
    y = drawSectionTitle(doc, y, 'OCCUPANCY TREND')
    y = drawTable(doc, y,
      ['Month', 'Occupancy %'],
      chartData.map(d => [d.month_label || '-', `${d.occupancy ?? 0}%`])
    )
  }

  if (filteredBookingStatusDist && filteredBookingStatusDist.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'BOOKING STATUS')
    const total = filteredBookingStatusDist.reduce((s, d) => s + (d.count || 0), 0) || 1
    y = drawTable(doc, y,
      ['Status', 'Count', 'Percentage'],
      filteredBookingStatusDist.map(d => [
        d.status || '-',
        String(d.count ?? 0),
        `${((d.count / total) * 100).toFixed(1)}%`,
      ])
    )
  }

  if (filteredPropertyPerformance && filteredPropertyPerformance.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'PROPERTY PERFORMANCE')
    y = drawTable(doc, y,
      ['Property', 'Bookings', 'Revenue', 'Rating'],
      filteredPropertyPerformance.map(p => [
        p.title || '-',
        String(p.total_bookings ?? 0),
        formatRupees(p.revenue ?? 0),
        p.avg_rating > 0 ? `${p.avg_rating}` : '-',
      ]),
      { columnStyles: { 2: { halign: 'right' } } }
    )
  }

  if (recentBookings && recentBookings.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'RECENT BOOKINGS')
    y = drawTable(doc, y,
      ['Booking ID', 'Guest', 'Property', 'Check-in', 'Check-out', 'Guests', 'Status', 'Amount'],
      recentBookings.map(b => [
        `#${b.id ?? b.booking_id ?? '-'}`,
        b.guest_name || '-',
        b.property_title || '-',
        b.check_in || '-',
        b.check_out || '-',
        String(b.guests_count ?? b.guests ?? 1),
        b.status || '-',
        formatRupees(b.total_price ?? 0),
      ]),
      { columnStyles: { 7: { halign: 'right' } } }
    )
  }

  if (checkins && checkins.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'UPCOMING CHECK-INS')
    y = drawTable(doc, y,
      ['Guest', 'Property', 'Check-in', 'Guests'],
      checkins.map(c => [
        c.guest_name || '-',
        c.property_title || '-',
        c.check_in || '-',
        String(c.guests_count ?? c.guests ?? 1),
      ])
    )
  }

  if (reviews && reviews.length > 0) {
    y = checkPageBreak(doc, y, 40, headerTitle)
    y = drawSectionTitle(doc, y, 'RECENT REVIEWS')
    y = drawTable(doc, y,
      ['Guest', 'Property', 'Rating', 'Review', 'Date'],
      reviews.map(r => [
        r.guest_name || '-',
        r.property_title || '-',
        `${r.rating ?? 0}/5`,
        (r.comment || '-').substring(0, 60) + (r.comment && r.comment.length > 60 ? '...' : ''),
        r.created_at ? r.created_at.split(' ')[0] : '-',
      ])
    )
  }

  y = drawDisclaimer(doc, y)
  addFooters(doc)

  doc.save(`StaySpace-Host-Report-${formatDate(now).replace(/\s/g, '-')}.pdf`)
}
